version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: .codedeploy/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: .codedeploy/change_permissions
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .codedeploy/start_server
    - location: .codedeploy/create_test_db
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .codedeploy/stop_server
      timeout: 300
      runas: root